---
title: "HW4 - La Quinta is Spanish for next to Denny’s"
author:
- Cecily Abraham
- Jonathan Bryan
- Ran Zhou
- Ting Dai
output: 
  html_document: 
    highlight: pygments
    theme: flatly
---

### Load the data

```{r setup, include=FALSE}
library(rvest)
library(maps)
library(ggplot2)
load("data/dennys.Rdata")
load("data/lq.Rdata")
```


###Web scraping
The html was scraped from the the local copy of the La Quinta HQ website. The full html was read into a string and then the hotel listing information from the html was isolated and stored. 




###Get the distance

```{r}
#Cited from distHaversine in geosphere package
distHaversine = function (p1, p2, r = 6378137) 
{
    toRad <- pi/180
    p1 <- p1 * toRad
    p2 <- p2 * toRad
    p = cbind(p1[, 1], p1[, 2], p2[, 1], p2[, 2], as.vector(r))
    dLat <- p[, 4] - p[, 2]
    dLon <- p[, 3] - p[, 1]
    a <- sin(dLat/2) * sin(dLat/2) + cos(p[, 2]) * cos(p[, 4]) * 
        sin(dLon/2) * sin(dLon/2)
    dist <- 2 * atan2(sqrt(a), sqrt(1 - a)) * p[, 5]
    return(as.vector(dist))
}
dist = list()
near_lq = rep(NA, nrow(dennys))
L = hotels[,c("long","lat")]
for(i in 1:nrow(dennys)){
  df1 = matrix(rep(c(dennys[[i,"long"]], dennys[[i, "lat"]]), nrow(L)), ncol=2, byrow=T)
  df2 = as.matrix(L)
  dis = distHaversine(df1, df2)
  dist[[i]] = dis
  near_lq[i] = sum(dis<100)
}

dennys$near_lq = near_lq
#load us map data
all_states = map_data("state")

#Plot all states with ggplot
ggplot() + 
  geom_polygon( data=all_states, aes(x=long, y=lat, group = group),colour="white", fill="khaki1" ) +
  geom_point(data = dennys[dennys$near_lq==0,], aes(x = long, y=lat, colour = "no")) +
  geom_point(data = dennys[dennys$near_lq>0,], aes(x = long, y=lat, colour = "yes")) +
  scale_color_manual(name = 'Have La Quintas nearby',
                     labels = c("no","yes"),
                     values = c("cadetblue2", 'red')) +
  ggtitle("Map of Dennys with La Quintas nearby") 
```

